kind: VirtualClusterTemplate
apiVersion: management.loft.sh/v1
metadata:
  name: pull-request-vcluster
spec:
  displayName: Pull Request vCluster
  description: >-
    Used for ephemeral vCluster instances for GitHub pull requests and includes an Argo CD instance installed in the vCluster.
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro:
      enabled: true
    helmRelease:
      chart:
        version: 0.20.0
      values: |-
        sync:
          toHost:
            ingresses:
              enabled: true
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  versions:
    - version: 1.0.0
      template:
        metadata:
          annotations:
            sleepmode.loft.sh/ignore-user-agents: argo*
        instanceTemplate:
          metadata:
            annotations:
              loft.sh/custom-links: >-
                https://argocd-{{ .Values.loft.virtualClusterName }}.{{ .Values.loft.clusterAnnotations.domain }}
        apps:
          # Argo CD vCluster Platform App - installs Argo CD into vCluster with Helm - see ../apps/argo-cd.yaml
          - name: argocd
            version: 2.14.1
            namespace: argocd
            parameters: "appValues: |\n  global:\n    # domain needs to be set if you want to use OIDC based SSO\n    # the .Values.loft.clusterAnnotations.domain is set on the vCluster Platform Cluster resource - see https://github.com/loft-demos/loft-demo-base/blob/main/vcluster-platform-demo-generator/vcluster-platform-gitops/apps/apps.yaml#L404-L405\n    domain: argocd-{{ .Values.loft.virtualClusterName }}.{{ .Values.loft.clusterAnnotations.domain }}\n  configs:\n    cm:\n      create: true\n      # the cm.url is required to make the Argo CD OIDC SSO work\n      url: https://argocd-{{ .Values.loft.virtualClusterName }}.{{ .Values.loft.clusterAnnotations.domain }}\n      application.resourceTrackingMethod: annotation\n      # OIDC config uses vCluster Platform as an OIDC Provider - see https://www.vcluster.com/docs/platform/how-to/oidc-provider\n      oidc.config: |\n         issuer: https://{{ .Values.loft.clusterAnnotations.domainPrefix }}.{{ .Values.loft.clusterAnnotations.domain }}/oidc\n         clientID: argocd-{{ .Values.loft.virtualClusterName }}\n         # this same OIDC clientSecret is also added to the vCluster Platform OIDC provider Secret resource\n         # The Crossplane composition adds that secret here: vcluster-gitops/crossplane/vcluster-pull-request-environment/vcluster-pull-request-environment-composition.yaml#L72-L131\n         clientSecret: $oidc-secret:clientSecret\n         name: Loft\n    params:\n      \"server.insecure\": true\n      timeout.reconciliation: 0  \n    secret:\n      createSecret: true\n    rbac:\n      policy.csv: |-\n        g, Administration, role:admin\n        g, Sales, role:admin\n        g, Engineering, role:admin\n  server:\n    ingress:\n      enabled: true\n      annotations:\n        nginx.ingress.kubernetes.io/force-ssl-redirect: \"true\"\n        nginx.ingress.kubernetes.io/backend-protocol: \"HTTP\"\n      ingressClassName: \"nginx\"\n      hostname: argocd-{{ .Values.loft.virtualClusterName }}.{{ .Values.loft.clusterAnnotations.domain }}\n      tls: true\n    ingressGrpc:\n      enabled: false\n  controller:\n    resources:\n      limits:\n        cpu: 1000m\n        memory: 2Gi\n      requests:\n        cpu: 250m\n        memory: 512Mi\n  ## ApplicationSet controller\n  applicationSet:\n    enabled: true\n    logLevel: \"debug\"\n    ingress:\n      enabled: true\n      ingressClassName: \"nginx\"\n      annotations:\n        nginx.ingress.kubernetes.io/force-ssl-redirect: \"true\"\n      hostname: argocd-appset-{{ .Values.loft.virtualClusterName }}.{{ .Values.loft.clusterAnnotations.domain }}\n      tls: true\n  notifications:\n    argocdUrl: https://argocd-{{ .Values.loft.virtualClusterName }}.{{ .Values.loft.clusterAnnotations.domain }}\n    cm:\n      create: true\n    context:\n      helloAppUrl: \"https://{{ .Values.loft.virtualClusterName }}.{{ .Values.loft.clusterAnnotations.domain }}\"\n    logLevel: \"debug\"\n    secret:\n      # label triggers the use of a vCluster Platform Project secret\n      labels:\n        loft.sh/project-secret-name: argocd-notifications-secret\n"
          # vCluster Platform App (Bash type) used to create the Argo CD ApplicationSet used to deploy the Pull Request application Helm chart
          - name: argo-cd-pr-application-set
            namespace: argocd
            parameters: |
              argocdUrl: >-
                https://argocd-{{ .Values.loft.virtualClusterName }}.{{
                .Values.loft.clusterAnnotations.domain }}
              vClusterName: '{{ .Values.loft.virtualClusterName }}'
              repoName: '{{ .Values.reponame }}'
        objects: |-
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argocd
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: loft-demo-org-cred
            namespace: argocd
            labels:
              loft.sh/project-secret-name: loft-demo-org-cred
              argocd.argoproj.io/secret-type: repo-creds
          type: Opaque
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: oidc-secret
            namespace: argocd
            labels:
              loft.sh/project-secret-name: oidc-secret
              app.kubernetes.io/part-of: argocd
          type: Opaque
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: preview-hello-world-app
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: ghcr-login-secret
            namespace: preview-hello-world-app
            labels:
              loft.sh/project-secret-name: ghcr-login-secret
          data:
            .dockerconfigjson: e30K
          type: kubernetes.io/dockerconfigjson
        pro:
          enabled: true
        helmRelease:
          chart:
            version: 0.26.0
          values: |
            external:
              platform:
                autoSleep:
                  afterInactivity: 7200
                autoDelete:
                  afterInactivity: 720000
            sync:
              toHost:
                ingresses:
                  enabled: true
            controlPlane:
              # Use an embedded managed etcd server instead of using the k3s default SQLite backend
              backingStore:
                etcd:
                  embedded:
                    enabled: true
              distro:
                k8s:
                  image:
                    tag: "{{ .Values.k8sVersion }}"
              coredns:
                embedded: true
        accessPoint:
          ingress: {}
        spaceTemplate:
          metadata: {}
      parameters:
        - variable: prnumber
          label: PR Number
          type: string
          defaultValue: '1'
        - variable: reponame
          label: Repo Name
          type: string
          defaultValue: hello-app
          label: Sleep After Inactivity (minutes)
          type: number
          options:
            - '30'
            - '45'
            - '60'
            - '120'
          defaultValue: '45'
          label: k8sVersion
          description: Please select Kubernetes version
          options:
            - v1.33.3
            - v1.32.7
            - v1.31.11
            - v1.30.14
          defaultValue: v1.32.7


