apiVersion: management.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: vcluster-pss-admission-config
spec:
  displayName: Virtual Cluster Template with Pod Security Admission Config
  description: This template deploys a vCluster with Pod Security Standards configured via the Kubernetes API server Pod Security Admission Controller configuration passed to the vCluster Kubernetes kube-apiserver.
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro:
      enabled: true
    helmRelease:
      chart:
        version: 0.26.0
      values: "controlPlane:\n  coredns:\n    embedded: true\n  distro:\n    k8s:\n      apiServer:\n        # \n        extraArgs:\n          - \"--admission-control-config-file=/etc/kubernetes/pod-security-admission-config.yaml\"\n  statefulSet:\n    persistence:\n      addVolumes:\n        - name: pod-security-admission-config\n          configMap:\n            name: pod-security-admission-config\n      addVolumeMounts:\n        - name: pod-security-admission-config\n          mountPath: /etc/kubernetes\n          readOnly: true\nsync:\n  fromHost:\n    runtimeClasses:\n      enabled: true\n  toHost:\n    ingresses:\n      enabled: true\n"
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
      objects: "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: pod-security-admission-config\ndata:\n  pod-security-admission-config.yaml: |-\n    apiVersion: apiserver.config.k8s.io/v1\n    kind: AdmissionConfiguration\n    plugins:\n    - name: PodSecurity\n      configuration:\n        apiVersion: pod-security.admission.config.k8s.io/v1 # see compatibility note\n        kind: PodSecurityConfiguration\n        # Defaults applied when a mode label is not set.\n        #\n        # Level label values must be one of:\n        # - \"privileged\" (default)\n        # - \"baseline\"\n        # - \"restricted\"\n        #\n        # Version label values must be one of:\n        # - \"latest\" (default) \n        # - specific version like \"v1.32\"\n        defaults:\n          enforce: \"baseline\"\n          enforce-version: \"latest\"\n          audit: \"baseline\"\n          audit-version: \"latest\"\n          warn: \"baseline\"\n          warn-version: \"latest\"\n        exemptions:\n          # Array of authenticated usernames to exempt.\n          usernames: []\n          # Array of runtime class names to exempt.\n          runtimeClasses: \n            - vnode\n          # Array of namespaces to exempt.\n          namespaces: []\n"
  access:
    - verbs:
        - get
      users:
        - '*'
