apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/

patches:
  - path: patch-k8s-version.yaml
    target:
      kind: VirtualClusterTemplate
      labelSelector: patchType=non-versioned
  - path: patch-k8s-versioned.yaml
    target:
      kind: VirtualClusterTemplate
      labelSelector: patchType=versioned
