apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-flux-ignore-to-storage-vci
spec:
  validationFailureAction: Enforce
  rules:
    - name: add-ignore-annotation
      match:
        all:
          - resources:
              kinds:
                - storage.loft.sh/*/VirtualClusterInstance
              operations:
                - CREATE
                - UPDATE
              selector:
                matchExpressions:
                  - key: kustomize.toolkit.fluxcd.io/name
                    operator: Exists
      exclude:
        any:
          - resources:
              kinds:
                - management.loft.sh/*/VirtualClusterInstance
      mutate:
        patchesJson6902: |-
          - op: delete
            path: "/metadata/labels"
