---
apiVersion: repo.github.upbound.io/v1alpha1
kind: IssueLabels
metadata:
  name: romeo-app-repo-labels
spec:
  deletionPolicy: Delete
  forProvider:
    label:
      - name: create-pr-vcluster-external-argocd
        color: ee7d3b
        description: Triggers the creation of a vCluster for a Pull Request via Argo CD
      - name: preview
        color: ee7d3b
        description: Creates vCluster preview environment for a Pull Request with a GitHub Action and Argo CD AppSet
      - name: 'deploy/argocd-vcluster-preview'
        color: ee7d3b
        description: Triggers the creation of a matrix of vCluster instances for different Kubernetes versions
      - name: preview-cluster-ready
        color: ee7d3b
        description: Triggers ArgoCD application set for PR
      - name: 'deploy/flux-vcluster-preview'
        color: c5def5
        description: Triggers Flux creation of vCluster pull request environment
      - name: e2e
        color: ee7d3b
        description: Run e2e tests on PR with vCluster
    repository: romeo-app
  initProvider: {}
  managementPolicies:
    - '*'
  providerConfigRef:
    name: github-provider-config
---
