---
apiVersion: management.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: sleepy-vcluster-template
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  displayName: Sleepy vCluster Template
  description: This template deploys a sleepy virtual cluster
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro:
      enabled: true
    helmRelease:
      chart:
        name: vcluster
        repo: https://loft-demos.github.io/vcluster-charts
        version: 0.22.4
      values: |
        sync:
          toHost:
            ingresses:
              enabled: true

        controlPlane:
          backingStore:
            etcd:
              embedded:
                enabled: true
          coredns:
            embedded: true
          statefulSet:
            image:
              repository: "loft-demos/vcluster-pro"
              tag: "0.22.4-k8s.{{ .Values.k8sVersion }}"
        
        external:
          platform:
            autoSleep:
              afterInactivity: {{ mul .Values.sleepAfter 60 }}
            autoDelete:
              afterInactivity: {{ mul .Values.sleepAfter 120 }}
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  parameters:
    - variable: sleepAfter
      label: Sleep After Inactivity (minutes)
      type: number
      defaultValue: '2'
    - variable: k8sVersion
      label: k8sVersion
      description: Please select Kubernetes version
      options:
        - v1.32.2
        - v1.31.6
        - v1.30.10
        - v1.29.14
      defaultValue: v1.31.6
  access:
    - verbs:
        - get
      users:
        - '*'
