- variable: sleepAfter
  label: Sleep After Inactivity (minutes)
  type: number
  options:
    - '30'
    - '45'
    - '60'
    - '120'
  defaultValue: '45'

- variable: k8sVersion
  label: k8sVersion
  description: Please select Kubernetes version
  options:
    - v1.33.1
    - v1.32.5
    - v1.31.9
    - v1.30.13
  defaultValue: v1.32.5