apiVersion: management.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: argo-cd-vcluster
spec:
  displayName: Argo CD vCluster
  description: >-
    Creates a vCluster instance with Argo CD for use within a vCluster Platform Project.
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata:
        annotations:
          loft.sh/custom-links: |-
            Argo-CD=https://{{ .Values.loft.virtualClusterName }}-{{ .Values.loft.project }}-{{ .Values.loft.clusterAnnotations.domainPrefix }}.{{ .Values.loft.clusterAnnotations.domain }}
            GitOps-Repo=https://github.com/{REPLACE_ORG_NAME}/{{ .Values.loft.clusterAnnotations.domainPrefix }}-app/
    apps:
      - name: argocd
        version: 2.14.10
        parameters: "appValues: |-\n  global:\n    domain: {{ .Values.loft.virtualClusterName }}-{{ .Values.loft.project }}-{{ .Values.loft.clusterAnnotations.domainPrefix }}.{{ .Values.loft.clusterAnnotations.domain }}\n  configs:\n    cm:\n      url: https://{{ .Values.loft.virtualClusterName }}-{{ .Values.loft.project }}-{{ .Values.loft.clusterAnnotations.domainPrefix }}.{{ .Values.loft.clusterAnnotations.domain }}\n      create: true\n      application.resourceTrackingMethod: annotation\n    params:\n      \"server.insecure\": true\n      timeout.reconciliation: 0 \n    rbac:\n      policy.csv: |-\n        g, Administration, role:admin\n        g, Sales, role:admin\n        g, Engineering, role:admin\n  server:\n    ingress:\n      enabled: true\n      annotations:\n        nginx.ingress.kubernetes.io/force-ssl-redirect: \"true\"\n        nginx.ingress.kubernetes.io/backend-protocol: \"HTTP\"\n      ingressClassName: \"nginx\"\n      hostname: {{ .Values.loft.virtualClusterName }}-{{ .Values.loft.project }}-{{ .Values.loft.clusterAnnotations.domainPrefix }}.{{ .Values.loft.clusterAnnotations.domain }}\n      tls: true\n    ingressGrpc:\n      enabled: false\n  ## ApplicationSet controller\n  applicationSet:\n    enabled: true\n    logLevel: \"debug\"\n    ingress:\n      enabled: true\n      ingressClassName: \"nginx\"\n      annotations:\n        nginx.ingress.kubernetes.io/force-ssl-redirect: \"true\"\n      hostname: {{ .Values.loft.virtualClusterName }}-{{ .Values.loft.project }}-{{ .Values.loft.clusterAnnotations.domainPrefix }}-appset.{{ .Values.loft.clusterAnnotations.domain }}\n      tls: true\n  notifications:\n    argocdUrl: https://{{ .Values.loft.virtualClusterName }}-{{ .Values.loft.project }}-{{ .Values.loft.clusterAnnotations.domainPrefix }}.{{ .Values.loft.clusterAnnotations.domain }}\n    cm:\n      create: true\n    logLevel: \"debug\"\n    secret:\n      labels:\n        loft.sh/project-secret-name: argocd-notifications-secret\n"
      - name: argo-cd-cluster-application-set
    objects: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: loft-demo-org-cred
        namespace: argocd
        labels:
          loft.sh/project-secret-name: loft-demo-org-cred
          argocd.argoproj.io/secret-type: repo-creds
      type: Opaque
      ---
    pro:
      enabled: true
    helmRelease:
      chart:
        version: 0.26.0
      values: |
        sleepMode:
          enabled: true
          autoSleep:
            schedule: 0 22 * * *
          timeZone: America/New_York
          autoWakeup:
            schedule: 0 6 * * 1-5
        external:
          platform:
            autoDelete:
              afterInactivity: 18000000
        sync:
          toHost:
            ingresses:
              enabled: true
            customResources:
              argocdwebhooks.demo.loft.sh:
                enabled: true

        controlPlane:
          # Use an embedded managed etcd server instead of using the default SQLite backend
          backingStore:
            etcd:
              embedded:
                enabled: true
          coredns:
            enabled: true
            embedded: true
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
      objects: |-
        apiVersion: v1
        kind: Secret
        metadata:
          name: argo-webhook-url
        type: Opaque
        stringData:
          url: "https://{{ .Values.loft.virtualClusterName }}-{{ .Values.loft.project }}-{{ .Values.loft.clusterAnnotations.domainPrefix }}.{{ .Values.loft.clusterAnnotations.domain }}/api/webhook"
        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: argo-appset-webhook-url
        type: Opaque
        stringData:
          url: "https://{{ .Values.loft.virtualClusterName }}-{{ .Values.loft.project }}-{{ .Values.loft.clusterAnnotations.domainPrefix }}-appset.{{ .Values.loft.clusterAnnotations.domain }}/api/webhook"
