apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-env-config
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values: ["dev"]
            - key: prNumber
              operator: DoesNotExist
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values: ["qa"]
            - key: prNumber
              operator: DoesNotExist
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values: ["prod"]
            - key: prNumber
              operator: DoesNotExist
  template:
    metadata:
      name: romeo-app-{{.name}}
    spec:
      destination:
        namespace: romeo-app-{{.metadata.labels.env}}
        server: '{{.server}}'
      info:
        - name: GitHub Repo
          value: https://github.com/loft-demos/romeo-app/
      project: 'loft-{{ index .metadata.labels "demos.loft.sh/project" }}'
      source:
        path: vcluster-use-cases/argocd-vcluster-add-ons/manifests/{{.metadata.labels.env}}/
        repoURL: https://github.com/loft-demos/romeo-app.git
        targetRevision: main
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - CreateNamespace=true
